config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  root to: "photos#index"

  get 'users/new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'users/:id', to: 'users#show'
  get '/users/:user_id/articles/:article_id/likes/new(.:format)', to: 'likes#new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resources :users do 
    resources :articles do 
      resources :likes
      resources :comments
    end
  end

  resources :articles do 
    resources :likes
    resources :comments
  end

  # resources :articles do
  #   resources :comments
  # end

  delete "delete_upload/:id", to: 'uploads#delete_upload', as: 'delete_upload', action: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    validates :title, presence: true,
                    length: { minimum: 5 }
    validates :user_id, presence: true

    has_many_attached :uploads

    def as_json(option = {})
        super(options.merge(include: [:user, comments: {include: :user}, likes: {include: :user}]))
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
    belongs_to :user

    def as_json(options = {})
        super(options.merge(include: :user))
    end
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    scope :recent, -> { where('created_at > ?', 1.week.ago)}
    validates :email, uniqueness: true, presence: true
    has_many :articles
    has_many :likes
    has_many :liked_articles, :through => :like, :source => :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end

    def require_valid_user! 
        if current_user.nil?
            flash[:error] = "You must be logged in to access that page"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :require_valid_user!

    def new 
        @article = Article.new
    end 

    def index
        @article = Article.all
    end
    
    def edit
        @article = Article.find(params[:id])
    end

    def show
        @article = Article.find(params[:id])
    end

    def create
        @article = ::ArticleServices::NewArticlesService.new(params, current_user.id).call
        if @article.save
            redirect_to @article
        else
            render :new
        end
    end

    def update
        # @article = ::ArticleServices::UpdateArticleService.new(params, current_user.id).call
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article
        else 
            render 'edit'
        end
    end

    def destroy
        @article = ::ArticleServices::DestroyArticlesService.new(params, current_user.id).call
        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :text, :user_id, uploads: [])
        end
end

app/controllers/avatar_controller.rb
class AvatarController < ApplicationController
    def new
        @user = current_user.id
    end

    def edit  
        @avatar = User.find(params[user_id]).avatar
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @comment = ::CommentServices::NewCommentService.new(params, current_user).call
        redirect_to article_path(params[:article_id])
    end

    def edit
        @article = Article.find(params[:article_id])
        @comment = Article.joins(:comments)
    end

    def update
        @article = Article.find(params[:article_id])
        @comment = ::CommentServices::UpdateCommentService.new(params).call
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = ::CommentServices::DestroyCommentService.new(params).call
        redirect_to article_path(@article)
    end

    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def new
        @like = Like.new(like_params)
    end
    
    def create 
        @user = current_user.id
        @article = params[:article_id]
        likes = {user_id: @user, article_id: @article}
        @like = Like.new(likes)
        if Like.where(user_id: @user, article_id: @article).present?
            redirect_to article_path(@article)
        else
            @like.save!
            if @like.save 
                redirect_to article_path(@article)
            end

        end
    end

    def destroy 
        @like = Like.where(user_id: @user, article_id: @article)
    end

    private
    def like_params
        params.require(:likes).permit(:user_id, :article_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_action :require_valid_user!, except: [:destroy]

  def new
  end

  def create
    @user = User.find_by(email: [sessions_params[:email]])

    if @user && @user.authenticate(sessions_params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "logged in"
    else
      flash[:error] = 'Wrong email and password combination'
      redirect_to login_path
    end
  end

  def destroy
    reset_session
  end

private
  def sessions_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
    def delete_upload
        @image = @image = Article.find(params[:id]).uploads
        @image.purge

        # redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :require_valid_user!
  # before_action :reset_session

  def new
    @user = User.new
  end

  def show 
    @user = User.find(params[:id])
    if @user
      @comments = Comment.where(:user_id => @user.id)
      @article = Article.where(:user_id => @user.id)
      @likes = Like.where(:user_id => @user.id)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    redirect_to user_path(@user)
  end

  def create
    @user = User.new(user_params)

    if @user.save!
      flash[:success] = "You have successfully created an account. Please sign in to continue"
      redirect_to login_path
    else
      render :new
    end
  end

  def logged_in?
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def nav_links
        item = [home_link, profile, logout]
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
    def displayCommentOptions(comment)
        if current_user.id == comment.user.id
            return true
        end
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_edit_form.html.haml
= form_with model: @article do |form|
    -# - if @article.errors.any?
    -#     %div{:id => "errors-explanation"}
    -#         %h2
    -#             = pluralize(@article.errors.count, 'errors')
    -#         %ul
    -#             - @article.errors.full_messages.each do |error|
    -#                 %li= error       
    %div
        = form.label :title
        = form.text_field :title, :class => 'form-control'
    %div
        = form.label :text
        = form.text_area :text, :class => 'form-control'
    %div
        = form.label :uploads
        = form.file_field :uploads, :class => 'form-control'
    %div#upload
        - @article.uploads.each do |upload|
            = image_tag(upload.variant(resize: "400x400"))
    %div
        = form.submit :class => 'btn btn-primary'

    

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@article.errors.count, "errors") %>
                Prohibited this from being saved:
            </h2>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>
    <p>
        <%= form.label :text %><br>
        <%= form.text_area :text %>
    </p>

    <p>
        <%= form.submit %>
    </p>

    <% end %>

app/views/articles/_form.html.haml
= form_with model: Article.new do |form|
    -# - if @article.errors.any?
    -#     %div{:id => "errors-explanation"}
    -#         %h2
    -#             = pluralize(@article.errors.count, 'errors')
    -#         %ul
    -#             - @article.errors.full_messages.each do |error|
    -#                 %li= error       
    %div
        = form.label :title
        = form.text_field :title, :class => 'form-control'
    %div
        = form.label :text
        = form.text_area :text, :class => 'form-control'
    %div
        = form.submit :class => 'btn btn-primary'

    

app/views/articles/_new_form.html.haml
= form_with model: Article.new do |form|
    -# - if @article.errors.any?
    -#     %div{:id => "errors-explanation"}
    -#         %h2
    -#             = pluralize(@article.errors.count, 'errors')
    -#         %ul
    -#             - @article.errors.full_messages.each do |error|
    -#                 %li= error       
    %div
        = form.label :title
        = form.text_field :title, :class => 'form-control'
    %div
        = form.label :text
        = form.text_area :text, :class => 'form-control'
    %div
        = form.label :uploads
        = form.file_field :uploads, :class => 'form-control'
    %div
        = form.submit :class => 'btn btn-primary'

    = link_to 'Back to articles', articles_path, method: :get

    

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render :partial => 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/edit.html.haml
%h1= "Edit Article"

= render :partial => "edit_form"

= link_to "back", articles_path

app/views/articles/index.html.erb
<% if flash[:success] %>
    <%= flash[:success] %>
<% end %>
<h1>Listing all articles</h1>
<%= link_to 'New Article', new_article_path %>
<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th></th>
    </tr>
    
    <% @article.each do |article| %>
        <tr>
            <td><%= article.title %></td>
            <td><%= article.text %></td>
            <td><%= link_to 'Show', article_path(article), method: :get %></td>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Destroy', article_path(article), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
        <% end %>
</table>

app/views/articles/index.html.haml
= render 'shared/nav_bar'
%div.jumbotron.jumbotron-fluid
    .container    
        %h1.display-4= "The Kitchen Sink"

%div.container-fluid
    %button.btn.btn-primary.btn-block{"data-toggle" => "collapse", "href" => "#newArticle"}
        New Article
    %div#newArticle.collapse
        = render :partial => "new_form"
- @article.each do |article|
    .card
        %h5.card-title= article.title
        .card-text= article.text
        - article.uploads.each do |upload|
            %div.media
                = image_tag upload.variant(resize: "150x150"), class: "mr-3"
        %div
            = link_to 'Show', article_path(article), method: :get, class: "btn btn-primary btn-sm"
            -# - if article.user_id == current_user.id
            -#     %button.btn.btn-primary{"data-toggle" => "collapse", "href" => "#editArticle"}
            -#         Edit Article
            -#     %div#editArticle.collapse
            -#         = render :partial => "edit_form", :locals => { article: article.id }
                = link_to 'Edit', edit_article_path(article), class: "btn btn-primary btn-sm", :locals => { article: article.id }
                = link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-sm"
            %hr      
%div
    = link_to 'Log Out', logout_path, class: "btn btn-primary"

app/views/articles/new.html.erb
<h1>New Article<h1>

<%= render :partial => 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/new.html.haml
%h1= "New Article"

= render :partial => "new_form"

= link_to "back", articles_path

app/views/articles/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @article.title %><br>

<p>
    <strong>Text:</strong>
    <%= @article.text %>
    <%= link_to 'Like', user_article_likes_path(@user, @article), method: :post %>
</p>

    <strong>Posted by: </strong><%= @article.user.email %>

    <h4>Comments</h4>
    <div>
        <%= render @article.comments %>
    </div>

<h2>Add a comment</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>
<%= link_to 'Log Out', logout_path %>

app/views/articles/show.html.haml
%div.jumbotron
    %h1.display-4= @article.title
    %p.lead= @article.text
    - @article.uploads.each do |upload|
        - if upload.variable?
            = link_to image_tag(upload.variant(resize: "400x400")), upload
            - if current_user.id == @article.user_id
                = link_to 'Remove', delete_upload_path(upload_id: @article.id), method: :delete
    %hr.my-4
    %div.container
        %div.col-sm
            %strong= "Posted by: "
            %strong= link_to @article.user.email, user_path(@article.user_id)
            %small=" @ "
            %small=@article.updated_at
            - if @article.updated_at != @article.created_at
                %small.badge.badge-dark=" Edited "
        - if current_user.id != @article.user_id
            %div.btn.btn-outline-primary.btn-sm= link_to 'Like', user_article_likes_path(current_user.id, @article), method: :post
        = link_to 'Delete Article', user_article_path( current_user.id, @article.id) , method: :delete

%div.container
    %h4.alert.alert-primary= "Comments"
    %div= render @article.comments

%div.container
    %h2.alert.alert-primary= "Add a comment"
    = render 'comments/form'

%div
    - if current_user.id == @article.user_id
        = link_to 'Edit', edit_article_path(@article)
    = link_to 'Back', articles_path, :class => 'btn btn-outline-primary', :id => 'back-btn'
    = link_to 'Log Out', logout_path , :class => 'btn btn-outline-primary', :id => 'logout-btn'

app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= link_to 'Profile', user_path(comment.user_id) %>
    <strong><%= comment.user.email %> </strong>
</p>

<p>
    <strong>Title:</strong>
    <%= comment.commenter %><br>
</p>

<p>
    <strong>Comment:</strong>
    <%= comment.body %>
</p>

<p>
    <%= link_to 'Edit', edit_article_comment_path(comment.article, comment) %><br>
    <%= link_to 'Destroy Comment', [comment.article, comment], method: :delete, data: {confirm: 'are you sure?'} %>
</p>

app/views/comments/_comment.html.haml
%div.card

    %div.card-text
        = comment.body
        %div
            %strong="By: "
            %strong= link_to comment.user.email, user_path(comment.user_id)
        %div
            %small=" at "
            %small= comment.updated_at
- if displayCommentOptions(comment)
    %div.card-text
        %small.btn.btn-outline-primary.btn-sm= link_to 'Edit', edit_article_comment_path(comment.article, comment)
        %small.btn.btn-outline-primary.btn-sm= link_to 'Delete', [comment.article, comment], method: :delete, data: {confirm: 'are you sure?'}

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
    <p>
        <%= form.label :commenter %><br>
        <%= form.text_field :commenter %>
    </p>

    <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
    </p>
    <p>
        <%= form.submit %>
    </p>

<% end %>

app/views/comments/_form.html.haml
= form_with(model: [ @article, @article.comments.build ], local: true) do |form|
    %div.input-group
        %div.input-group-prepend
            %span.input-group-text= current_user.email
        = form.text_area :body, :class => 'form-control'
    %div
        = form.submit :submit, class: 'btn btn-primary btn-lg'

app/views/comments/edit.html.haml
%h1= "Edit Comment"

= form_with(model: [@article, @article.comments.find(params[:id])], local: true) do |form|

    %div
        = form.label :commenter
        = form.text_field :commenter

    %div
        = form.label :body
        = form.text_area :body

    %div
        = form.submit

app/views/comments/erb/edit.html.erb
<h1>Edit Comment</h1>

<%= form_with(model: [@article, @article.comments.find(params[:id])], local: true) do |form| %>
    <p>
        <%= form.label :commenter %><br>
        <%= form.text_field :commenter %>
    </p>

    <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
    </p>
    <p>
        <%= form.submit %>
    </p>

<% end %>

app/views/users/_articles.html.haml
%h3.alert.alert-primary="Articles: "
%div
    - @article.each do |article|
        %div.card
            %dl
                %dt.card-title
                    %a{:href => articles_path(@article)} 
                        = article.title
                %dd.card-text
                    = article.text

app/views/users/_comments.html.haml
%h3.alert.alert-primary="Comments: "
%div
    - @comments.each do |comment|
        %div.card
            %dl
                %dt.card-subtitle
                    = comment.commenter
                %dd.card-text 
                    = comment.body
                = link_to @article.find(comment.article_id).title, articles_path(comment.article_id)

app/views/users/_likes.html.haml
%div 
    %h3.alert.alert-primary= "Likes"
    - @likes.each do |like|
        %div.btn.btn-outline-dark
            = link_to @article.find(like.article_id).title, articles_path(like.article_id)

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.haml
%div
    = form_for @user, :url => {:action => 'update'}, :html => { :multipart => true } do |user_form|
        %div
            = user_form.label :avatar
            = user_form.file_field :avatar
        %div
            = user_form.submit "upload"

app/views/users/new.html.erb
<h1>Sign Up</h1>
<p>Create a new account using the form below. All fields are required.</p>

<% if @user.errors.any? %>
    <div class='alert alert-danger'>
        <p>Please correct the following errors: </p>
        <ul>
            <% @user.errors.full_messages.each do |error_msg| %>
                <li><%= error_msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for @user do |user_form| %>
    <div class='form-group'>
        <%= user_form.label :email %>
        <%= user_form.email_field :email, class: 'form-control' %>
    </div>
    <div class='form-group'>
        <%= user_form.label :password %>
        <%= user_form.password_field :password, class: 'form-control' %>
    </div>
    <div class='form-group'>
        <%= user_form.label :password_confirmation %>
        <%= user_form.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= user_form.label :avatar %>
        <%= user_form.file_field :avatar, class: 'form-control' %>
    </div>
    <%= user_form.submit 'Register', class: 'btn btn-primary'%>
<% end %>

<p class='mt-2'>
    Already have an account? <%= link_to 'Click here to login', login_path %>
</p>

app/views/users/show.html.erb
<p>
    <h1>Profile View</h1>
    <strong>User</strong>
    <%= @user.email %><br>
    <%= image_tag(@user.avatar) %>
    <strong>User ID: </strong><%= @user.id %>  

<%= render :partial => "articles" %>

<%= render :partial => "comments" %>

<%= render :partial => "likes" %>

<p>
    <%= link_to 'Back to articles', articles_path, method: :get %>
</p>

app/views/users/show.html.haml
%div
    %h1="Profile View"
    %strong="User: "
    = @user.email
    %strong="User I.D: " + @user.id.to_s

%div
    = image_tag(@user.avatar) if @user.avatar.attached?
    = form_for @user, :action => 'update' do |user_form|
        %div
            = user_form.label :avatar
            = user_form.file_field :avatar
        %div
            = user_form.submit "upload"
    

%div
    = render :partial => "articles"
%div
    = render :partial => "comments"
%div
    = render :partial => "likes"

= link_to 'Back to articles', articles_path, method: :get

= link_to 'Edit Profile', user_path, method: :put